//ERROR
export const SET_ERRORS = "SET_ERRORS"
export const SET_ERRORS_HELPER = "SET_ERRORS_HELPER"
export const SET_FLAG = "SET_FLAG"

//ADMIN
export const SET_ADMIN = "SET_ADMIN"
export const GET_SUBJECTS = "GET_SUBJECTS"



//FACULTY
export const SET_FACULTY = "SET_FACULTY"
export const FACULTY_UPDATE_PASSWORD = "FACULTY_UPDATE_PASSWORD"

//STUDENT
export const SET_STUDENT = "SET_STUDENT"
export const STUDENT_UPDATE_PASSWORD = "STUDENT_UPDATE_PASSWORD"
export const SET_OTP = "SET_OTP"

//TASKS
export const GET_TODOS_REQUEST = "GET_TODOS_REQUEST";
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS";
export const GET_TODOS_FAILURE = "GET_TODOS_FAILURE";

export const POST_TODOS_REQUEST = "POST_TODOS_REQUEST";
export const POST_TODOS_SUCCESS = "POST_TODOS_SUCCESS";
export const POST_TODOS_FAILURE = "POST_TODOS_FAILURE";

export const DELETE_TODOS_REQUEST = "DELETE_TODOS_REQUEST";
export const DELETE_TODOS_SUCCESS = "DELETE_TODOS_SUCCESS";
export const DELETE_TODOS_FAILURE = "DELETE_TODOS_FAILURE";

